[theme]
primaryColor = "#FDB833"
backgroundColor = "#F5F5F5"
secondaryBackgroundColor = "#1E1E1E"
textColor = "#0A0A0A"
font = "sans serif"

[client]
showErrorDetails = true
toolbarMode = "minimal"

[logger]
level = "info"

[ui]
hideTopBar = false
hideFooter = true
hideSidebarNav = false
